### ISSUE TITLE
ParenthesisCheck

### ISSUE THREAD

**Issue by pavelapk** [DmitryTsyvtsyn/Kotlin-Algorithms-and-Design-Patterns#8]
https://github.com/evitwilly/Kotlin-Algorithms-and-Design-Patterns/blob/develop/src/main/kotlin/other/ParenthesisCheck.kt

В алгоритме не учтен случай, когда в конце строки открывающие скобки, например `[[` или `()[`

**Comment by DmitryTsyvtsyn** [comment]
Пофиксил, спасибо) Чекайте)
